### ISSUE TITLE
TP7: Porque hay que seleccionar 2 veces 3 puntos?

### ISSUE THREAD

**Issue by jaarac** [franco11696/vision#2]
Hay que seleccionar 3 puntos en una imagen y en esos 3 puntos insertar otra imagen en base a una transformacion afin.

**Comment by franco11696** [comment]
Se modificó el programa para que solo se seleccionen los 3 puntos de destino en la imágen final. Ahora solo se debe seleccionar la opción "a" del menú y marcar donde se quiere insertar el logo utilizando la transformación afin.
